Repository RA-MPR/mpr, pull requests merged in 2021-04, with the labels that each got.

#58 Show company detail on row click
  frontend/src/Components/CompanyDetails/CompanyDetails.jsx
  frontend/src/Components/CompanyList/CompanyList.css
  frontend/src/Components/CompanyList/CompanyList.jsx
  frontend/src/Components/CompanyPage.js
Labels: development

#59 Fixed problems from Discord
  frontend/src/Components/AppBar/AppBar.js
  frontend/src/Components/CompanyNew/CompanyNew.css
  frontend/src/Components/CompanyNew/CompanyNew.jsx
  frontend/src/Components/CompanyNew/StatusPicker.css
  frontend/src/Components/CompanyNew/StatusPicker.jsx
  frontend/src/Components/CompanyPage.css
  frontend/src/Components/NotFound/NotFound.css
  frontend/src/Components/NotFound/NotFound.jsx
  frontend/src/index.css
  frontend/src/index.js
Labels: bug, development

#68 New company validation hotfix
  frontend/src/Components/CompanyNew/CompanyNew.jsx
Labels: bug

#71 Add contact list
  frontend/src/Components/AppBar/AppBar.js
  frontend/src/Components/ContactList/ContactList.css
  frontend/src/Components/ContactList/ContactList.jsx
  frontend/src/Components/ContactList/ContactListHeader.jsx
  frontend/src/Components/ContactPage.css
  frontend/src/Components/ContactPage.js
  frontend/src/index.js
Labels: development

#82 Order list and order management in company detail
  frontend/package.json
  frontend/src/Components/CompanyDetails/CompanyDetails.jsx
  frontend/src/Components/CompanyDetails/ConfirmDialog.jsx
  frontend/src/Components/CompanyDetails/Orders.jsx
  frontend/src/Components/CompanyDetails/css/CompanyDetails.css
  frontend/src/Components/CompanyDetails/css/Orders.css
Labels: development

#84 Update company list
  frontend/src/Components/CompanyList/CompanyList.jsx
  frontend/src/Components/CompanyPage.js
Labels: development

#87 Company details events
  frontend/src/Components/CompanyDetails/CompanyDetails.jsx
  frontend/src/Components/CompanyDetails/Events.jsx
  frontend/src/Components/CompanyDetails/css/Events.css
Labels: development

#91 Small batch of FE fixes
  frontend/src/Components/AppBar/AppBar.css
  frontend/src/Components/AppBar/AppBar.js
  frontend/src/Components/CompanyDetails/CompanyInformations.jsx
  frontend/src/Components/CompanyDetails/ContactPersons.jsx
  frontend/src/Components/CompanyDetails/Events.jsx
  frontend/src/Components/CompanyDetails/Notes.jsx
  frontend/src/Components/CompanyDetails/css/Orders.css
  frontend/src/Components/CompanyPage.css
  frontend/src/Components/ContactPage.css
  frontend/src/Components/Footer/Footer.css
Labels: enhancement

#109 Add token authorization
  frontend/src/Components/CompanyDetails/CompanyDetails.jsx
  frontend/src/Components/CompanyDetails/CompanyInformations.jsx
  frontend/src/Components/CompanyDetails/ContactPersons.jsx
  frontend/src/Components/CompanyDetails/Events.jsx
  frontend/src/Components/CompanyDetails/Orders.jsx
  frontend/src/Components/CompanyDetails/StatusChange.jsx
  frontend/src/Components/CompanyList/CompanyList.jsx
  frontend/src/Components/CompanyNew/CompanyNew.jsx
  frontend/src/Components/CompanyPage.js
  frontend/src/Components/ContactList/ContactList.jsx
  frontend/src/Components/ContactPage.js
Labels: development

#110 Fix null user in company list
  frontend/src/Components/CompanyList/CompanyList.jsx
Labels: bug

#111 upcoming events component (with GET/events)
  frontend/src/Components/CompanyDetails/CompanyDetails.jsx
  frontend/src/Components/CompanyDetails/Events.jsx
  frontend/src/Components/CompanyPage.js
  frontend/src/Components/ContactPage.js
  frontend/src/Components/UpcomingEvents/UpcomingEvents.css
  frontend/src/Components/UpcomingEvents/UpcomingEvents.jsx
Labels: development

#119 Add separate routing for every element
  frontend/src/App.js
  frontend/src/Components/CompanyDetails/CompanyDetails.jsx
  frontend/src/Components/CompanyPage.js
  frontend/src/Components/ContactPage.js
  frontend/src/index.js
Labels: development

#122 small FE fixes
  frontend/src/Components/CompanyDetails/CompanyDetails.jsx
  frontend/src/Components/CompanyDetails/ContactPersons.jsx
  frontend/src/Components/CompanyDetails/Events.jsx
  frontend/src/Components/CompanyDetails/StatusChange.jsx
  frontend/src/Components/CompanyDetails/css/Events.css
  frontend/src/Components/CompanyDetails/css/StatusChange.css
  frontend/src/Components/CompanyList/CompanyList.jsx
  frontend/src/Components/CompanyNew/CompanyNew.jsx
  frontend/src/Components/CompanyPage.js
  frontend/src/Components/UpcomingEvents/UpcomingEvents.css
  frontend/src/Components/UpcomingEvents/UpcomingEvents.jsx
Labels: bug, development

#128 Handle row click in contact list
  frontend/src/App.js
  frontend/src/Components/ContactList/ContactList.jsx
  frontend/src/Components/ContactPage.js
Labels: development

#133 Orders graph (year/quarter)
  frontend/package.json
  frontend/src/Components/CompanyDetails/CompanyDetails.jsx
  frontend/src/Components/CompanyDetails/Orders.jsx
  frontend/src/Components/CompanyPage.js
  frontend/src/Components/Graph/Graph.css
  frontend/src/Components/Graph/Graph.jsx
Labels: development

#134 Add new/edit event dialog
  frontend/src/Components/Calendar/Calendar.css
  frontend/src/Components/Calendar/EventDialog.jsx
  frontend/src/Components/CalendarPage.js
Labels: development

#135 Connected new/edit event dialog
  frontend/src/Components/Calendar/Calendar.css
  frontend/src/Components/Calendar/EventDialog.jsx
  frontend/src/Components/Calendar/EventsOfTheDay.jsx
  frontend/src/Components/CalendarPage.js
  frontend/src/Components/CompanyDetails/Events.jsx
  frontend/src/Components/CompanyDetails/css/Events.css
  frontend/src/Components/UpcomingEvents/UpcomingEvents.css
  frontend/src/Components/UpcomingEvents/UpcomingEvents.jsx
Labels: development

#142 Some FE fixes
  frontend/src/App.js
  frontend/src/Components/AppBar/AppBar.js
  frontend/src/Components/Calendar/Calendar.jsx
  frontend/src/Components/Calendar/EventDialog.jsx
  frontend/src/Components/CalendarPage.js
  frontend/src/Components/CompanyDetails/CompanyDetails.jsx
  frontend/src/Components/CompanyDetails/CompanyInformations.jsx
  frontend/src/Components/CompanyDetails/Events.jsx
  frontend/src/Components/CompanyDetails/Orders.jsx
  frontend/src/Components/CompanyDetails/StatusChange.jsx
  frontend/src/Components/CompanyDetails/css/CompanyDetails.css
  frontend/src/Components/CompanyList/CompanyList.jsx
  frontend/src/Components/Graph/Graph.jsx
Labels: bug

#141 Admin user list
  backend/users/admin.py
  frontend/src/App.js
  frontend/src/Components/UserList/UserList.css
  frontend/src/Components/UserList/UserList.jsx
  frontend/src/Components/UserList/UserListHeader.jsx
  frontend/src/Components/UserPage.css
  frontend/src/Components/UserPage.js
Labels: development

#143 User form
  frontend/src/Components/UserFormDialog/UserFormDialog.css
  frontend/src/Components/UserFormDialog/UserFormDialog.jsx
  frontend/src/Components/UserList/UserList.jsx
  frontend/src/Components/UserPage.js
Labels: development

#145 FE fixes
  frontend/src/App.js
  frontend/src/Components/CompanyDetails/Orders.jsx
  frontend/src/Components/CompanyList/CompanyList.jsx
  frontend/src/Components/CompanyPage.js
  frontend/src/Components/Graph/Graph.css
  frontend/src/Components/Graph/Graph.jsx
  frontend/src/Components/UserFormDialog/UserFormDialog.jsx
Labels: bug

#147 added matrix
  frontend/src/App.js
  frontend/src/Components/CalendarPage.js
  frontend/src/Components/CompanyPage.js
  frontend/src/Components/ContactPage.js
  frontend/src/Components/MatrixPage.css
  frontend/src/Components/MatrixPage.js
  frontend/src/Components/UpcomingEvents/UpcomingEvents.jsx
  frontend/src/Components/UserPage.js
Labels: bug, development

#149 Company list fixes
  backend/company/serializers/common.py
  frontend/src/Components/AppBar/AppBar.js
  frontend/src/Components/CompanyDetails/CompanyDetails.jsx
  frontend/src/Components/CompanyDetails/Orders.jsx
  frontend/src/Components/CompanyList/CompanyList.jsx
  frontend/src/Components/CompanyPage.js
Labels: bug
